[[redirects]]
  from = "/api/*"
  to = "https://nodejs311.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200